<!-- App.svelte -->
<script>
    export let title = 'Lyric Generator';
  </script>
  
  <head>
    <title>{title}</title>
  </head>
  
 
  <header>
    <div class="header-container">
      <div class="header-wrapper">
        <h1 class="title">{title}</h1>
        <p class="subtitle">Lyrics generated with AI</p>
      </div>
    </div>
  </header>
  
  <main>
  <div class="container">
    <div class="ads">
      <!-- ad code here -->
    </div>
  
    <section>
      <h2 class="subtitle">Do you struggle with writing lyrics for your songs? Look no further than Lyric Generator!</h2>
      <p>Our powerful AI algorithm will help you create catchy and meaningful lyrics in no time. Simply input a few keywords, and our software will do the rest.</p>
    </section>
  
    <section>
      <h2 class="subsubtitle">How it Works</h2>
      <ol>
        <li>Choose a genre that has lyrics, like 60's pop or psychedelic folk.</li>
        <li>Enter a subject for your song. This can be a single word or a whole line!</li>
        <li>Choose an artist you want the lyrics to sound like.</li>
        <li>Be creative! What would a New Wave version of Kendrick Lamar sound like? A reggaeton version of Nirvana?</li>

        <li>Click the "Generate Lyrics" button.</li>
        <li>Enjoy your new lyrics!</li>
      </ol>
    </section>

  
    
    
  <div class="wrapper">

    <div class="input-wrapper-left">
      <label for="genre-input">Genre:</label>
      <div class="input-container">
        <input type="text" id="genre-input" placeholder="Enter your genre...">
        <span class="input-icon"><i class="fas fa-music"></i></span>
      </div>
    </div>
    
    <div class="input-wrapper-center">
      <label for="subject-input">Subject:</label>
      <div class="input-container-top">
        <span class="input-icon"><i class="fas fa-lightbulb"></i></span>
        <input type="text" id="subject-input" placeholder="Enter your subject...">
      </div>
    </div>
    
    <div class="input-wrapper-right">
      <label for="artist-input">Artist:</label>
      <div class="input-container-right">
        <input type="text" id="artist-input" placeholder="Enter your artist...">
        <span class="input-icon"><i class="fas fa-user"></i></span>
      </div>
    </div>
    
    <button class="generator-btn">g e n e r a t e &nbsp; l y r i c s</button>
  </div>

    <div class="ads">
      <!-- ad code here -->
    </div>
  
    <section>
      <h2 class="subsubtitle">Benefits of Using Lyric Generator</h2>
      <ul>
        <li><h3>Save time and effort</h3>Never again will you have to struggle to come up with the perfect words to match your melody. Lyric Generator does the hard work for you, leaving you free to focus on what really matters - making music!</li>
        <li><h3>Improve the quality of your lyrics</h3>Our AI algorithm takes your input and generates lyrics that are not only catchy but also meaningful. Say goodbye to generic and uninspired lyrics, and hello to truly original and impactful songwriting.</li>
        <li><h3>Explore new topics and themes</h3>Lyric Generator provides a wealth of inspiration and ideas for your songwriting. Whether you're looking to write a love ballad or a protest anthem, our software can help you explore new topics and themes to create truly unique and memorable songs.</li>
        <li><h3>Find inspiration for new songs</h3>Stuck in a creative rut? Lyric Generator can help! Our powerful software generates fresh and exciting lyrics that can inspire you to create your next hit song.</li>
      </ul>
    </section>
    <section>
      <h2 class="sub-section-title">What Our Users Are Saying</h2>
      <div class="border"></div>
      <div class="testimonial-container">
        <div class="testimonial-wrapper">
          <div class="testimonial">
            <p class="testimonial-text">"As someone who struggles with writing lyrics, Lyric Generator has been a game-changer. I highly recommend it to anyone looking to improve their songwriting."</p>
            <p class="testimonial-author">- Alex James, Singer-Songwriter</p>
          </div>
    
          <div class="testimonial">
            <p class="testimonial-text">"I was blown away by how accurate and relevant the lyrics generated by Lyric Generator were. It's like the software could read my mind!"</p>
            <p class="testimonial-author">- Sarah Parker, Music Producer</p>
          </div>
    
          <div class="testimonial">
            <p class="testimonial-text">"I've tried other lyric generators before, but Lyric Generator is by far the best. It's easy to use and produces amazing results."</p>
            <p class="testimonial-author">- David Lee, Singer</p>
          </div>
    
          <div class="testimonial">
            <p class="testimonial-text">"Thanks to Lyric Generator, I've been able to write more songs in less time. It's truly a lifesaver!"</p>
            <p class="testimonial-author">- Maria Rodriguez, Musician</p>
          </div>
        </div>
      </div>
    </section>
    
  </div>
</main>

  <footer>
    <p>Lyric Generator 2023 - Version 0.1.0</p>
  </footer>

  <style>
 
    main {
      display: flex;
      flex-direction: column;
      align-items: center;
      text-align: center;
      padding: 1rem;
      max-width: 800px;
      margin: 0 auto;
      background-color: #334155;
    }
    ol {
      /* list-style-position: inside; */
      list-style-type: none; /* remove the default numbering */
      padding-left: 1em; /* add some left padding for the list items */

    }
    ul {
      list-style-position: inside;

    }
    li {
      text-align: center;
      margin-bottom: 0.5em; /* add some space between list items */

}   
.wrapper {
  position:relative;
display:flex;
justify-content: center; 
align-items: flex-start;
  margin: 1rem;
  padding: 1rem;
  border: 1px solid #ccc;
  border-radius: 1.5rem;
  max-width: 800px;
  height: 400px;
}


    .ads {
      display: flex;
      justify-content: space-between;
      margin: 1rem 0;
    }
  
    .header-container {
    
      border-bottom: 1px solid #ccc;
      display: flex;
      flex-direction: column;
      align-items: center;
      padding: 1rem;
      max-width: 800px;
      margin: 0 auto;
      background-color: #334155;
    }
  
    .header-wrapper {
      text-align: center;
      padding-bottom: 1rem;
      margin-bottom: 2rem;
    }
  
    .title {
      font-size: 4rem;
      font-family: Arial, sans-serif;
      margin: 0;
  }

  .subtitle {
    font-size: 1.5rem;
    margin: 0;
    color: #888;
    text-align: center;
    color: #9ca3af
  }

  .subsubtitle {
    font-size: 2rem;
    margin: 1rem 0 0.5rem;
    font-weight: bold;
    text-align: center;
  }
  .sub-section-title {
    text-align: center;
    font-weight: bold
  }

  footer {
    text-align: center;
    margin-top: 2rem;
    display: flex;
      flex-direction: column;
      align-items: center;
      padding: 1rem;
      max-width: 800px;
      margin: 0 auto;
      background-color: #334155;
  }
  .testimonial-container {
  display: flex;
  justify-content: center;
  align-items: center;
  margin-top: 1rem;
}

.testimonial-wrapper {
  display: flex;
  flex-wrap: wrap;
  justify-content: space-evenly;
}

.testimonial {
  margin: 1rem;
  padding: 1rem;
  border: 1px solid #ccc;
  border-radius: 1.5rem;
  width: 300px;
  height: 200px;
}

.testimonial-text {
  font-style: italic;
}

.testimonial-author {
  text-align: right;
  font-weight: bold;
  margin-top: 0.5rem;
  margin-bottom: 0;
}
/* Input styling */
.input-wrapper-center {
  display: flex;
  flex-direction: column;
  margin-bottom: 1rem;
  position: absolute;
}
.input-wrapper-left {
  display: flex;
  flex-direction: column;
  margin-bottom: 1rem;
  position: absolute;
  left: 0%
}
.input-wrapper-right {
  display: flex;
  flex-direction: column;
  margin-bottom: 1rem;
  position: absolute;
  right: 0%
}

.input-container {
  position: relative;
}

input[type="text"] {
  padding: 0.5rem 2rem 0.5rem 0.5rem;
  border-radius: .5rem;
  background-color: #0f172a;
  transition: all 0.2s ease-in-out;
  width: 100%;
  max-width: 8rem;
  margin: 2rem;
  margin-top: 0rem;
  top: 0%;
  left: 0%
}
input::placeholder {
  color: #e5e7eb
}

input:focus {
  /* border-color: #e5e7eb; */
  outline: 1px solid #e5e7eb;

}

input[type="text"]:focus {
  border: 1px solid #e5e7eb;
  /* box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3); */
}

label {
  margin-bottom: 0.5rem;
}

.input-icon {
  position: absolute;
  right: 0.5rem;
  top: 50%;
  transform: translateY(-50%);
  color: #e5e7eb
}

.input-icon i {
  font-size: 1rem;
}

.input-icon:hover {
  color: #e5e7eb;
}

/* Button styling */
.generator-btn {
  display: inline-block;
  border: none;
  transition: all 0.2s ease-in-out;
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translateX(-50%);
  background-color: #fb8200;
     padding: 2rem;
      width: 16rem;
      max-width: 18rem;
      max-height: 5rem;
      box-shadow: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1);
      border-radius: 1.5rem;
      color:#0f172a;
}

.generator-btn:hover {
  transform: translateY(-1px);
  box-shadow: 0 3px 6px rgba(0, 0, 0, 0.2);
}

.generator-btn:active {
  transform: translateY(1px);
  box-shadow: none;
}


</style>  



