<script>
	import { onMount } from 'svelte';
	import { navigate } from 'svelte-routing';
	import { lyrics, loading } from '../../stores/OverlayStore.js';

	onMount(() => {
		if (!$lyrics) {
			navigate('/');
		}
	});
	let clicked = false;
	let newline = '\n \n \n';
	let tagline = 'generated by lyricgenerator.com';

	function copyText() {
		/* Copy selected text into clipboard */
		navigator.clipboard.writeText(`${$lyrics} ${newline} ${newline}${tagline}`);
	}
	function isClicked() {
		clicked = true;
		setTimeout(() => {
			clicked = false;
		}, 1500);
	}
</script>

<section class="container">
	{#if $loading}
		<a href="/">
			<i class="fa-solid fa-arrow-left-long arrow" />
		</a>
		<!-- svelte-ignore a11y-click-events-have-key-events -->

		<i
			class="fa-solid fa-copy copy-button"
			on:click={() => {
				copyText();
				isClicked();
			}}
		/>
		<span class="loading">
			<span class="letter" style="animation-delay: 0s;">t</span>
			<span class="letter" style="animation-delay: 0.1s;">h</span>
			<span class="letter" style="animation-delay: 0.2s;">i</span>
			<span class="letter" style="animation-delay: 0.3s;">n</span>
			<span class="letter" style="animation-delay: 0.4s;">k</span>
			<span class="letter" style="animation-delay: 0.5s;">i</span>
			<span class="letter" style="animation-delay: 0.6s;">n</span>
			<span class="letter" style="animation-delay: 0.7s;">g</span>
		</span>
	{/if}
	{#if !$loading}
		{#if !clicked}
			<span class="lyrics">{$lyrics} </span>
			<a href="/">
				<i class="fa-solid fa-arrow-left-long arrow" />
			</a>
			<!-- svelte-ignore a11y-click-events-have-key-events -->
			<i
				class="fa-solid fa-copy copy-button"
				on:click={() => {
					copyText();
					isClicked();
				}}
			/>
		{/if}
		{#if clicked}
			<span class="lyrics">{$lyrics} </span>
			<i class="fa-solid fa-arrow-left arrow" />
			<i class="fa-solid fa-copy copy-button-2" />
		{/if}
	{/if}
</section>

<style>
	.container {
		display: flex;
		justify-content: center;
		align-items: flex-start;
		height: 100%;
		width: 100%;
	}

	.lyrics {
		white-space: pre-wrap;
		line-height: 1.5rem;
		font-family: 'Courier New', Courier, monospace;
		color: #e5e7eb;
		text-align: center;
	}

	.loading {
		color: #e5e7eb;
		font-family: 'Courier New', Courier, monospace;
		text-align: center;
		margin-top: calc(40% - 20px); /* adjust this value to move the loading text down */
	}

	@keyframes loadingBounce {
		0%,
		100% {
			transform: translateY(0);
		}
		50% {
			transform: translateY(-10px);
		}
	}
	.letter {
		display: inline-block;
		animation: loadingBounce 1s infinite;
	}
	.arrow {
		position: absolute;
		top: 1.5rem;
		left: 1.5rem;
		cursor: pointer;
		font-family: 'Font Awesome 5 Free';
		font-style: regular;
		font-size: 1.5rem;
		color: #e5e7eb;
		opacity: 0.3;
		transition: opacity 300ms ease-in-out 300ms;
		margin: 1rem;
	}
	.arrow:hover {
		opacity: 1;
	}
	.copy-button {
		position: absolute;
		top: 1.5rem;
		right: 1.5rem;
		cursor: pointer;
		font-family: 'Font Awesome 5 Free';
		font-weight: 400;
		font-style: regular;
		font-size: 1.5rem;
		color: #e5e7eb;
		opacity: 0.3;
		transition: opacity 300ms ease-in-out 300ms;
		margin: 1rem;
	}
	.copy-button-2 {
		position: absolute;
		top: 1.5rem;
		right: 1.5rem;
		cursor: pointer;
		font-family: 'Font Awesome 5 Free';
		font-weight: 400;
		font-style: regular;
		font-size: 1.5rem;
		color: #10b981;
		opacity: 1;
		transition: opacity 300ms ease-in-out 300ms;
		margin: 1rem;
	}
	.copy-button:hover {
		opacity: 1;
	}

	section {
		position: relative;
	}
</style>
